const surah82 = [
  {
    id: '82_01_01',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذَا',
  },
  {
    id: '82_01_02',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّمَاءُ',
  },
  {
    id: '82_01_03',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'انْفَطَرَتْ‎﴿١﴾',
  },
  {
    id: '82_02_01',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '82_02_02',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكَوَاكِبُ',
  },
  {
    id: '82_02_03',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'انْتَثَرَتْ‎﴿٢﴾',
  },
  {
    id: '82_03_01',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '82_03_02',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'الْبِحَارُ',
  },
  {
    id: '82_03_03',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'فُجِّرَتْ‎﴿٣﴾',
  },
  {
    id: '82_04_01',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '82_04_02',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'الْقُبُورُ',
  },
  {
    id: '82_04_03',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'بُعْثِرَتْ‎﴿٤﴾',
  },
  {
    id: '82_05_01',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'عَلِمَتْ',
  },
  {
    id: '82_05_02',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'نَفْسٌ',
  },
  {
    id: '82_05_03',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_05_04',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'قَدَّمَتْ',
  },
  {
    id: '82_05_05',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَخَّرَتْ‎﴿٥﴾',
  },
  {
    id: '82_06_01',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'يَا',
  },
  {
    id: '82_06_02',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'أَيُّهَا',
  },
  {
    id: '82_06_03',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'الْإِنْسَانُ',
  },
  {
    id: '82_06_04',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_06_05',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'غَرَّكَ',
  },
  {
    id: '82_06_06',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'بِرَبِّكَ',
  },
  {
    id: '82_06_07',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكَرِيمِ‎﴿٦﴾',
  },
  {
    id: '82_07_01',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'الَّذِي',
  },
  {
    id: '82_07_02',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'خَلَقَكَ',
  },
  {
    id: '82_07_03',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'فَسَوَّاكَ',
  },
  {
    id: '82_07_04',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'فَعَدَلَكَ‎﴿٧﴾',
  },
  {
    id: '82_08_01',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'فِي',
  },
  {
    id: '82_08_02',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'أَيِّ',
  },
  {
    id: '82_08_03',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'صُورَةٍ',
  },
  {
    id: '82_08_04',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_08_05',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'شَاءَ',
  },
  {
    id: '82_08_06',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'رَكَّبَكَ‎﴿٨﴾',
  },
  {
    id: '82_09_01',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'كَلَّا',
  },
  {
    id: '82_09_02',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'بَلْ',
  },
  {
    id: '82_09_03',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'تُكَذِّبُونَ',
  },
  {
    id: '82_09_04',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'بِالدِّينِ‎﴿٩﴾',
  },
  {
    id: '82_10_01',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِنَّ',
  },
  {
    id: '82_10_02',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'عَلَيْكُمْ',
  },
  {
    id: '82_10_03',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'لَحَافِظِينَ‎﴿١٠﴾',
  },
  {
    id: '82_11_01',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'كِرَامًا',
  },
  {
    id: '82_11_02',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'كَاتِبِينَ‎﴿١١﴾',
  },
  {
    id: '82_12_01',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'يَعْلَمُونَ',
  },
  {
    id: '82_12_02',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_12_03',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'تَفْعَلُونَ‎﴿١٢﴾',
  },
  {
    id: '82_13_01',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّ',
  },
  {
    id: '82_13_02',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'الْأَبْرَارَ',
  },
  {
    id: '82_13_03',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'لَفِي',
  },
  {
    id: '82_13_04',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'نَعِيمٍ‎﴿١٣﴾',
  },
  {
    id: '82_14_01',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِنَّ',
  },
  {
    id: '82_14_02',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'الْفُجَّارَ',
  },
  {
    id: '82_14_03',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'لَفِي',
  },
  {
    id: '82_14_04',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'جَحِيمٍ‎﴿١٤﴾',
  },
  {
    id: '82_15_01',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'يَصْلَوْنَهَا',
  },
  {
    id: '82_15_02',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '82_15_03',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'الدِّينِ‎﴿١٥﴾',
  },
  {
    id: '82_16_01',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '82_16_02',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'هُمْ',
  },
  {
    id: '82_16_03',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'عَنْهَا',
  },
  {
    id: '82_16_04',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'بِغَائِبِينَ‎﴿١٦﴾',
  },
  {
    id: '82_17_01',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '82_17_02',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'أَدْرَاكَ',
  },
  {
    id: '82_17_03',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_17_04',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمُ',
  },
  {
    id: '82_17_05',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'الدِّينِ‎﴿١٧﴾',
  },
  {
    id: '82_18_01',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '82_18_02',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_18_03',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'أَدْرَاكَ',
  },
  {
    id: '82_18_04',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '82_18_05',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمُ',
  },
  {
    id: '82_18_06',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'الدِّينِ‎﴿١٨﴾',
  },
  {
    id: '82_19_01',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '82_19_02',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'لَا',
  },
  {
    id: '82_19_03',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'تَمْلِكُ',
  },
  {
    id: '82_19_04',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'نَفْسٌ',
  },
  {
    id: '82_19_05',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'لِنَفْسٍ',
  },
  {
    id: '82_19_06',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'شَيْئًا',
  },
  {
    id: '82_19_07',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'ۖ',
  },
  {
    id: '82_19_08',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْأَمْرُ',
  },
  {
    id: '82_19_09',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَئِذٍ',
  },
  {
    id: '82_19_10',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'لِلَّهِ‎﴿١٩﴾',
  },
];

export default surah82;
