const surah78 = [
  {
    id: '78_01_01',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'عَمَّ',
  },
  {
    id: '78_01_02',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'يَتَسَاءَلُونَ‎﴿١﴾',
  },

  {
    id: '78_02_01',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'عَنِ',
  },
  {
    id: '78_02_02',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'النَّبَإِ',
  },
  {
    id: '78_02_03',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'الْعَظِيمِ‎﴿٢﴾',
  },

  {
    id: '78_03_01',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'الَّذِي',
  },
  {
    id: '78_03_02',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'هُمْ',
  },
  {
    id: '78_03_03',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'فِيهِ',
  },
  {
    id: '78_03_04',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'مُخْتَلِفُونَ‎﴿٣﴾',
  },

  {
    id: '78_4_1',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'كَلَّا',
  },
  {
    id: '78_4_2',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'سَيَعْلَمُونَ‎﴿٤﴾',
  },

  {
    id: '78_5_1',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '78_5_2',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'كَلَّا',
  },
  {
    id: '78_5_3',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'سَيَعْلَمُونَ‎﴿٥﴾',
  },

  {
    id: '78_6_1',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'أَلَمْ',
  },
  {
    id: '78_6_2',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'نَجْعَلِ',
  },
  {
    id: '78_6_3',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'الْأَرْضَ',
  },
  {
    id: '78_6_4',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'مِهَادًا‎﴿٦﴾',
  },

  {
    id: '78_7_1',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْجِبَالَ',
  },
  {
    id: '78_7_2',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'أَوْتَادًا‎﴿٧﴾',
  },

  {
    id: '78_8_1',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'وَخَلَقْنَاكُمْ',
  },
  {
    id: '78_8_2',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'أَزْوَاجًا‎﴿٨﴾',
  },

  {
    id: '78_9_1',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'وَجَعَلْنَا',
  },
  {
    id: '78_9_2',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'نَوْمَكُمْ',
  },
  {
    id: '78_9_3',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'سُبَاتًا‎﴿٩﴾',
  },

  {
    id: '78_10_1',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'وَجَعَلْنَا',
  },
  {
    id: '78_10_2',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'اللَّيْلَ',
  },
  {
    id: '78_10_3',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'لِبَاسًا‎﴿١٠﴾',
  },

  {
    id: '78_11_1',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'وَجَعَلْنَا',
  },
  {
    id: '78_11_2',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'النَّهَارَ',
  },
  {
    id: '78_11_3',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'مَعَاشًا‎﴿١١﴾',
  },

  {
    id: '78_12_1',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'وَبَنَيْنَا',
  },
  {
    id: '78_12_2',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'فَوْقَكُمْ',
  },
  {
    id: '78_12_3',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'سَبْعًا',
  },
  {
    id: '78_12_4',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'شِدَادًا‎﴿١٢﴾',
  },

  {
    id: '78_13_1',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'وَجَعَلْنَا',
  },
  {
    id: '78_13_2',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'سِرَاجًا',
  },
  {
    id: '78_13_3',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'وَهَّاجًا‎﴿١٣﴾',
  },

  {
    id: '78_14_1',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَنْزَلْنَا',
  },
  {
    id: '78_14_2',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنَ',
  },
  {
    id: '78_14_3',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمُعْصِرَاتِ',
  },
  {
    id: '78_14_4',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'مَاءً',
  },
  {
    id: '78_14_5',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'ثَجَّاجًا‎﴿١٤﴾',
  },

  {
    id: '78_15_1',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'لِنُخْرِجَ',
  },
  {
    id: '78_15_2',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'بِهِ',
  },
  {
    id: '78_15_3',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'حَبًّا',
  },
  {
    id: '78_15_4',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'وَنَبَاتًا‎﴿١٥﴾',
  },

  {
    id: '78_16_1',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'وَجَنَّاتٍ',
  },
  {
    id: '78_16_2',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'أَلْفَافًا‎﴿١٦﴾',
  },

  {
    id: '78_17_1',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّ',
  },
  {
    id: '78_17_2',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '78_17_3',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'الْفَصْلِ',
  },
  {
    id: '78_17_4',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'كَانَ',
  },
  {
    id: '78_17_5',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'مِيقَاتًا‎﴿١٧﴾',
  },

  {
    id: '78_18_1',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '78_18_2',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'يُنْفَخُ',
  },
  {
    id: '78_18_3',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'فِي',
  },
  {
    id: '78_18_4',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'الصُّورِ',
  },
  {
    id: '78_18_5',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'فَتَأْتُونَ',
  },
  {
    id: '78_18_6',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'أَفْوَاجًا‎﴿١٨﴾',
  },

  {
    id: '78_19_1',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'وَفُتِحَتِ',
  },
  {
    id: '78_19_2',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّمَاءُ',
  },
  {
    id: '78_19_3',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'فَكَانَتْ',
  },
  {
    id: '78_19_4',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'أَبْوَابًا‎﴿١٩﴾',
  },

  {
    id: '78_20_1',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'وَسُيِّرَتِ',
  },
  {
    id: '78_20_2',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجِبَالُ',
  },
  {
    id: '78_20_3',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'فَكَانَتْ',
  },
  {
    id: '78_20_4',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'سَرَابًا‎﴿٢٠﴾',
  },

  {
    id: '78_21_1',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّ',
  },
  {
    id: '78_21_2',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'جَهَنَّمَ',
  },
  {
    id: '78_21_3',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'كَانَتْ',
  },
  {
    id: '78_21_4',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'مِرْصَادًا‎﴿٢١﴾',
  },

  {
    id: '78_22_1',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'لِلطَّاغِينَ',
  },
  {
    id: '78_22_2',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'مَآبًا‎﴿٢٢﴾',
  },
  {
    id: '78_23_1',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'لَابِثِينَ',
  },
  {
    id: '78_23_2',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'فِيهَا',
  },
  {
    id: '78_23_3',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'أَحْقَابًا‎﴿٢٣﴾',
  },
  {
    id: '78_24_1',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'لَا',
  },
  {
    id: '78_24_2',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'يَذُوقُونَ',
  },
  {
    id: '78_24_3',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'فِيهَا',
  },
  {
    id: '78_24_4',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'بَرْدًا',
  },
  {
    id: '78_24_5',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'وَلَا',
  },
  {
    id: '78_24_6',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'شَرَابًا‎﴿٢٤﴾',
  },
  {
    id: '78_25_1',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَّا',
  },
  {
    id: '78_25_2',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'حَمِيمًا',
  },
  {
    id: '78_25_3',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'وَغَسَّاقًا‎﴿٢٥﴾',
  },
  {
    id: '78_26_1',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'جَزَاءً',
  },
  {
    id: '78_26_2',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'وِفَاقًا‎﴿٢٦﴾',
  },
  {
    id: '78_27_1',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّهُمْ',
  },
  {
    id: '78_27_2',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'كَانُوا',
  },
  {
    id: '78_27_3',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'لَا',
  },
  {
    id: '78_27_4',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'يَرْجُونَ',
  },
  {
    id: '78_27_5',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'حِسَابًا‎﴿٢٧﴾',
  },
  {
    id: '78_28_1',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'وَكَذَّبُوا',
  },
  {
    id: '78_28_2',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'بِآيَاتِنَا',
  },
  {
    id: '78_28_3',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'كِذَّابًا‎﴿٢٨﴾',
  },
  {
    id: '78_29_1',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'وَكُلَّ',
  },
  {
    id: '78_29_2',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'شَيْءٍ',
  },
  {
    id: '78_29_3',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'أَحْصَيْنَاهُ',
  },
  {
    id: '78_29_4',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'كِتَابًا‎﴿٢٩﴾',
  },
  {
    id: '78_30_1',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'فَذُوقُوا',
  },
  {
    id: '78_30_2',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'فَلَنْ',
  },
  {
    id: '78_30_3',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'نَزِيدَكُمْ',
  },
  {
    id: '78_30_4',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَّا',
  },
  {
    id: '78_30_5',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'عَذَابًا‎﴿٣٠﴾',
  },
  {
    id: '78_31_1',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّ',
  },
  {
    id: '78_31_2',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'لِلْمُتَّقِينَ',
  },
  {
    id: '78_31_3',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'مَفَازًا‎﴿٣١﴾',
  },
  {
    id: '78_32_1',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'حَدَائِقَ',
  },
  {
    id: '78_32_2',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَعْنَابًا‎﴿٣٢﴾',
  },
  {
    id: '78_33_1',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'وَكَوَاعِبَ',
  },
  {
    id: '78_33_2',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'أَتْرَابًا‎﴿٣٣﴾',
  },
  {
    id: '78_34_1',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'وَكَأْسًا',
  },
  {
    id: '78_34_2',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'دِهَاقًا‎﴿٣٤﴾',
  },
  {
    id: '78_35_1',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'لَا',
  },
  {
    id: '78_35_2',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'يَسْمَعُونَ',
  },
  {
    id: '78_35_3',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'فِيهَا',
  },
  {
    id: '78_35_4',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'لَغْوًا',
  },
  {
    id: '78_35_5',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'وَلَا',
  },
  {
    id: '78_35_6',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'كِذَّابًا‎﴿٣٥﴾',
  },
  {
    id: '78_36_1',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'جَزَاءً',
  },
  {
    id: '78_36_2',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْ',
  },
  {
    id: '78_36_3',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبِّكَ',
  },
  {
    id: '78_36_4',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'عَطَاءً',
  },
  {
    id: '78_36_5',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'حِسَابًا‎﴿٣٦﴾',
  },
  {
    id: '78_37_1',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبِّ',
  },
  {
    id: '78_37_2',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّمَاوَاتِ',
  },
  {
    id: '78_37_3',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْأَرْضِ',
  },
  {
    id: '78_37_4',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '78_37_5',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'بَيْنَهُمَا',
  },
  {
    id: '78_37_6',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'الرَّحْمَٰنِ',
  },
  {
    id: '78_37_7',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'لَا',
  },
  {
    id: '78_37_8',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'يَمْلِكُونَ',
  },
  {
    id: '78_37_9',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْهُ',
  },
  {
    id: '78_37_10',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'خِطَابًا‎﴿٣٧﴾',
  },
  {
    id: '78_38_1',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '78_38_2',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'يَقُومُ',
  },
  {
    id: '78_38_3',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'الرُّوحُ',
  },
  {
    id: '78_38_4',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْمَلَائِكَةُ',
  },
  {
    id: '78_38_5',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'صَفًّا',
  },
  {
    id: '78_38_6',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'لَا',
  },
  {
    id: '78_38_7',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'يَتَكَلَّمُونَ',
  },
  {
    id: '78_38_8',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَّا',
  },
  {
    id: '78_38_9',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'مَنْ',
  },
  {
    id: '78_38_10',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'أَذِنَ',
  },
  {
    id: '78_38_11',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'لَهُ',
  },
  {
    id: '78_38_12',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'الرَّحْمَٰنُ',
  },
  {
    id: '78_38_13',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'وَقَالَ',
  },
  {
    id: '78_38_14',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'صَوَابًا‎﴿٣٨﴾',
  },
  {
    id: '78_39_1',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'ذَٰلِكَ',
  },
  {
    id: '78_39_2',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'الْيَوْمُ',
  },
  {
    id: '78_39_3',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'الْحَقُّ',
  },
  {
    id: '78_39_4',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'فَمَنْ',
  },
  {
    id: '78_39_5',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'شَاءَ',
  },
  {
    id: '78_39_6',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'اتَّخَذَ',
  },
  {
    id: '78_39_7',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَىٰ',
  },
  {
    id: '78_39_8',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبِّهِ',
  },
  {
    id: '78_39_9',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'مَآبًا‎﴿٣٩﴾',
  },
  {
    id: '78_40_1',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّا',
  },
  {
    id: '78_40_2',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْذَرْنَاكُمْ',
  },
  {
    id: '78_40_3',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'عَذَابًا',
  },
  {
    id: '78_40_4',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'قَرِيبًا',
  },
  {
    id: '78_40_5',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '78_40_6',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'يَنْظُرُ',
  },
  {
    id: '78_40_7',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمَرْءُ',
  },
  {
    id: '78_40_8',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '78_40_9',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'قَدَّمَتْ',
  },
  {
    id: '78_40_10',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'يَدَاهُ',
  },
  {
    id: '78_40_11',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'وَيَقُولُ',
  },
  {
    id: '78_40_12',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكَافِرُ',
  },
  {
    id: '78_40_13',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'يَا',
  },
  {
    id: '78_40_14',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'لَيْتَنِي',
  },
  {
    id: '78_40_15',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'كُنْتُ',
  },
  {
    id: '78_40_16',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'تُرَابًا‎﴿٤٠﴾',
  },
];

export default surah78;
