const surah79 = [
  {
    id: '79_01_01',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالنَّازِعَاتِ',
  },
  {
    id: '79_01_02',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'غَرْقًا‎﴿١﴾',
  },
  {
    id: '79_02_01',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالنَّاشِطَاتِ',
  },
  {
    id: '79_02_02',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'نَشْطًا‎﴿٢﴾',
  },
  {
    id: '79_03_01',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالسَّابِحَاتِ',
  },
  {
    id: '79_03_02',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'سَبْحًا‎﴿٣﴾',
  },
  {
    id: '79_04_01',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'فَالسَّابِقَاتِ',
  },
  {
    id: '79_04_02',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'سَبْقًا‎﴿٤﴾',
  },
  {
    id: '79_05_01',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'فَالْمُدَبِّرَاتِ',
  },
  {
    id: '79_05_02',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'أَمْرًا‎﴿٥﴾',
  },
  {
    id: '79_06_01',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '79_06_02',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'تَرْجُفُ',
  },
  {
    id: '79_06_03',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'الرَّاجِفَةُ‎﴿٦﴾',
  },
  {
    id: '79_07_01',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'تَتْبَعُهَا',
  },
  {
    id: '79_07_02',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'الرَّادِفَةُ‎﴿٧﴾',
  },
  {
    id: '79_08_01',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'قُلُوبٌ',
  },
  {
    id: '79_08_02',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَئِذٍ',
  },
  {
    id: '79_08_03',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'وَاجِفَةٌ‎﴿٨﴾',
  },
  {
    id: '79_09_01',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'أَبْصَارُهَا',
  },
  {
    id: '79_09_02',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'خَاشِعَةٌ‎﴿٩﴾',
  },
  {
    id: '79_10_01',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'يَقُولُونَ',
  },
  {
    id: '79_10_02',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'أَإِنَّا',
  },
  {
    id: '79_10_03',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'لَمَرْدُودُونَ',
  },
  {
    id: '79_10_04',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'فِي',
  },
  {
    id: '79_10_05',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'الْحَافِرَةِ‎﴿١٠﴾',
  },
  {
    id: '79_11_01',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'أَإِذَا',
  },
  {
    id: '79_11_02',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'كُنَّا',
  },
  {
    id: '79_11_03',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'عِظَامًا',
  },
  {
    id: '79_11_04',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'نَخِرَةً‎﴿١١﴾',
  },
  {
    id: '79_12_01',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'قَالُوا',
  },
  {
    id: '79_12_02',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'تِلْكَ',
  },
  {
    id: '79_12_03',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذًا',
  },
  {
    id: '79_12_04',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'كَرَّةٌ',
  },
  {
    id: '79_12_05',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'خَاسِرَةٌ‎﴿١٢﴾',
  },
  {
    id: '79_13_01',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'فَإِنَّمَا',
  },
  {
    id: '79_13_02',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'هِيَ',
  },
  {
    id: '79_13_03',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'زَجْرَةٌ',
  },
  {
    id: '79_13_04',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'وَاحِدَةٌ‎﴿١٣﴾',
  },
  {
    id: '79_14_01',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'فَإِذَا',
  },
  {
    id: '79_14_02',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'هُمْ',
  },
  {
    id: '79_14_03',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'بِالسَّاهِرَةِ‎﴿١٤﴾',
  },
  {
    id: '79_15_01',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'هَلْ',
  },
  {
    id: '79_15_02',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'أَتَاكَ',
  },
  {
    id: '79_15_03',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'حَدِيثُ',
  },
  {
    id: '79_15_04',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'مُوسَىٰ‎﴿١٥﴾',
  },
  {
    id: '79_16_01',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذْ',
  },
  {
    id: '79_16_02',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'نَادَاهُ',
  },
  {
    id: '79_16_03',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبُّهُ',
  },
  {
    id: '79_16_04',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'بِالْوَادِ',
  },
  {
    id: '79_16_05',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمُقَدَّسِ',
  },
  {
    id: '79_16_06',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'طُوًى‎﴿١٦﴾',
  },
  {
    id: '79_17_01',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'اذْهَبْ',
  },
  {
    id: '79_17_02',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَىٰ',
  },
  {
    id: '79_17_03',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'فِرْعَوْنَ',
  },
  {
    id: '79_17_04',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّهُ',
  },
  {
    id: '79_17_05',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'طَغَىٰ‎﴿١٧﴾',
  },
  {
    id: '79_18_01',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'فَقُلْ',
  },
  {
    id: '79_18_02',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'هَلْ',
  },
  {
    id: '79_18_03',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'لَكَ',
  },
  {
    id: '79_18_04',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَىٰ',
  },
  {
    id: '79_18_05',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْ',
  },
  {
    id: '79_18_06',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'تَزَكَّىٰ‎﴿١٨﴾',
  },
  {
    id: '79_19_01',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَهْدِيَكَ',
  },
  {
    id: '79_19_02',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَىٰ',
  },
  {
    id: '79_19_03',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبِّكَ',
  },
  {
    id: '79_19_04',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'فَتَخْشَىٰ‎﴿١٩﴾',
  },
  {
    id: '79_20_01',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَرَاهُ',
  },
  {
    id: '79_20_02',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'الْآيَةَ',
  },
  {
    id: '79_20_03',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكُبْرَىٰ‎﴿٢٠﴾',
  },

  {
    id: '79_21_01',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'فَكَذَّبَ',
  },
  {
    id: '79_21_02',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'وَعَصَىٰ‎﴿٢١﴾',
  },
  {
    id: '79_22_01',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '79_22_02',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'أَدْبَرَ',
  },
  {
    id: '79_22_03',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'يَسْعَىٰ‎﴿٢٢﴾',
  },
  {
    id: '79_23_01',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'فَحَشَرَ',
  },
  {
    id: '79_23_02',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'فَنَادَىٰ‎﴿٢٣﴾',
  },
  {
    id: '79_24_01',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'فَقَالَ',
  },
  {
    id: '79_24_02',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنَا',
  },
  {
    id: '79_24_03',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبُّكُمُ',
  },
  {
    id: '79_24_04',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'الْأَعْلَىٰ‎﴿٢٤﴾',
  },
  {
    id: '79_25_01',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَخَذَهُ',
  },
  {
    id: '79_25_02',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'اللَّهُ',
  },
  {
    id: '79_25_03',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'نَكَالَ',
  },
  {
    id: '79_25_04',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'الْآخِرَةِ',
  },
  {
    id: '79_25_05',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْأُولَىٰ‎﴿٢٥﴾',
  },
  {
    id: '79_26_01',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّ',
  },
  {
    id: '79_26_02',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'فِي',
  },
  {
    id: '79_26_03',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'ذَٰلِكَ',
  },
  {
    id: '79_26_04',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'لَعِبْرَةً',
  },
  {
    id: '79_26_05',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'لِمَنْ',
  },
  {
    id: '79_26_06',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'يَخْشَىٰ‎﴿٢٦﴾',
  },
  {
    id: '79_27_01',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'أَأَنْتُمْ',
  },
  {
    id: '79_27_02',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'أَشَدُّ',
  },
  {
    id: '79_27_03',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'خَلْقًا',
  },
  {
    id: '79_27_04',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'أَمِ',
  },
  {
    id: '79_27_05',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّمَاءُ',
  },
  {
    id: '79_27_06',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'بَنَاهَا‎﴿٢٧﴾',
  },
  {
    id: '79_28_01',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'رَفَعَ',
  },
  {
    id: '79_28_02',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'سَمْكَهَا',
  },
  {
    id: '79_28_03',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'فَسَوَّاهَا‎﴿٢٨﴾',
  },
  {
    id: '79_29_01',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَغْطَشَ',
  },
  {
    id: '79_29_02',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'لَيْلَهَا',
  },
  {
    id: '79_29_03',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَخْرَجَ',
  },
  {
    id: '79_29_04',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'ضُحَاهَا‎﴿٢٩﴾',
  },
  {
    id: '79_30_01',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْأَرْضَ',
  },
  {
    id: '79_30_02',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'بَعْدَ',
  },
  {
    id: '79_30_03',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'ذَٰلِكَ',
  },
  {
    id: '79_30_04',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'دَحَاهَا‎﴿٣٠﴾',
  },
  {
    id: '79_31_01',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'أَخْرَجَ',
  },
  {
    id: '79_31_02',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْهَا',
  },
  {
    id: '79_31_03',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'مَاءَهَا',
  },
  {
    id: '79_31_04',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَرْعَاهَا‎﴿٣١﴾',
  },
  {
    id: '79_32_01',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالْجِبَالَ',
  },
  {
    id: '79_32_02',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'أَرْسَاهَا‎﴿٣٢﴾',
  },
  {
    id: '79_33_01',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'مَتَاعًا',
  },
  {
    id: '79_33_02',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'لَكُمْ',
  },
  {
    id: '79_33_03',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'وَلِأَنْعَامِكُمْ‎﴿٣٣﴾',
  },
  {
    id: '79_34_01',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'فَإِذَا',
  },
  {
    id: '79_34_02',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'جَاءَتِ',
  },
  {
    id: '79_34_03',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'الطَّامَّةُ',
  },
  {
    id: '79_34_04',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكُبْرَىٰ‎﴿٣٤﴾',
  },
  {
    id: '79_35_01',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '79_35_02',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'يَتَذَكَّرُ',
  },
  {
    id: '79_35_03',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'الْإِنْسَانُ',
  },
  {
    id: '79_35_04',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '79_35_05',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'سَعَىٰ‎﴿٣٥﴾',
  },
  {
    id: '79_36_01',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'وَبُرِّزَتِ',
  },
  {
    id: '79_36_02',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجَحِيمُ',
  },
  {
    id: '79_36_03',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'لِمَنْ',
  },
  {
    id: '79_36_04',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'يَرَىٰ‎﴿٣٦﴾',
  },
  {
    id: '79_37_01',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَمَّا',
  },
  {
    id: '79_37_02',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'مَنْ',
  },
  {
    id: '79_37_03',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'طَغَىٰ‎﴿٣٧﴾',
  },
  {
    id: '79_38_01',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'وَآثَرَ',
  },
  {
    id: '79_38_02',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'الْحَيَاةَ',
  },
  {
    id: '79_38_03',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'الدُّنْيَا‎﴿٣٨﴾',
  },
  {
    id: '79_39_01',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'فَإِنَّ',
  },
  {
    id: '79_39_02',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجَحِيمَ',
  },
  {
    id: '79_39_03',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'هِيَ',
  },
  {
    id: '79_39_04',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمَأْوَىٰ‎﴿٣٩﴾',
  },
  {
    id: '79_40_01',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَمَّا',
  },
  {
    id: '79_40_02',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'مَنْ',
  },
  {
    id: '79_40_03',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'خَافَ',
  },
  {
    id: '79_40_04',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'مَقَامَ',
  },
  {
    id: '79_40_05',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبِّهِ',
  },
  {
    id: '79_40_06',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'وَنَهَىٰ',
  },
  {
    id: '79_40_07',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'النَّفْسَ',
  },
  {
    id: '79_40_08',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'عَنِ',
  },
  {
    id: '79_40_09',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'الْهَوَىٰ‎﴿٤٠﴾',
  },
  {
    id: '79_41_01',
    verseNumber: 41,
    startTime: 0,
    endTime: 1,
    ayah: 'فَإِنَّ',
  },
  {
    id: '79_41_02',
    verseNumber: 41,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجَنَّةَ',
  },
  {
    id: '79_41_03',
    verseNumber: 41,
    startTime: 0,
    endTime: 1,
    ayah: 'هِيَ',
  },
  {
    id: '79_41_04',
    verseNumber: 41,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمَأْوَىٰ‎﴿٤١﴾',
  },
  {
    id: '79_42_01',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'يَسْأَلُونَكَ',
  },
  {
    id: '79_42_02',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'عَنِ',
  },
  {
    id: '79_42_03',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّاعَةِ',
  },
  {
    id: '79_42_04',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'أَيَّانَ',
  },
  {
    id: '79_42_05',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'مُرْسَاهَا‎﴿٤٢﴾',
  },
  {
    id: '79_43_01',
    verseNumber: 43,
    startTime: 0,
    endTime: 1,
    ayah: 'فِيمَ',
  },
  {
    id: '79_43_02',
    verseNumber: 43,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْتَ',
  },
  {
    id: '79_43_03',
    verseNumber: 43,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْ',
  },
  {
    id: '79_43_04',
    verseNumber: 43,
    startTime: 0,
    endTime: 1,
    ayah: 'ذِكْرَاهَا‎﴿٤٣﴾',
  },
  {
    id: '79_44_01',
    verseNumber: 44,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَىٰ',
  },
  {
    id: '79_44_02',
    verseNumber: 44,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبِّكَ',
  },
  {
    id: '79_44_03',
    verseNumber: 44,
    startTime: 0,
    endTime: 1,
    ayah: 'مُنْتَهَاهَا‎﴿٤٤﴾',
  },
  {
    id: '79_45_01',
    verseNumber: 45,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّمَا',
  },
  {
    id: '79_45_02',
    verseNumber: 45,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْتَ',
  },
  {
    id: '79_45_03',
    verseNumber: 45,
    startTime: 0,
    endTime: 1,
    ayah: 'مُنذِرُ',
  },
  {
    id: '79_45_04',
    verseNumber: 45,
    startTime: 0,
    endTime: 1,
    ayah: 'مَنْ',
  },
  {
    id: '79_45_05',
    verseNumber: 45,
    startTime: 0,
    endTime: 1,
    ayah: 'يَخْشَاهَا‎﴿٤٥﴾',
  },
  {
    id: '79_46_01',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'كَأَنَّهُمْ',
  },
  {
    id: '79_46_02',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '79_46_03',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'يَرَوْنَهَا',
  },
  {
    id: '79_46_04',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'لَمْ',
  },
  {
    id: '79_46_05',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'يَلْبَثُوا',
  },
  {
    id: '79_46_06',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَّا',
  },
  {
    id: '79_46_07',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'عَشِيَّةً',
  },
  {
    id: '79_46_08',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'أَوْ',
  },
  {
    id: '79_46_09',
    verseNumber: 46,
    startTime: 0,
    endTime: 1,
    ayah: 'ضُحَاهَا‎﴿٤٦﴾',
  },
];

export default surah79;
