const surah80 = [
  {
    id: '80_01_01',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'عَبَسَ',
  },
  {
    id: '80_01_02',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'وَتَوَلَّىٰ‎﴿١﴾',
  },
  {
    id: '80_02_01',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْ',
  },
  {
    id: '80_02_02',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'جَاءَهُ',
  },
  {
    id: '80_02_03',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'الْأَعْمَىٰ‎﴿٢﴾',
  },
  {
    id: '80_03_01',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '80_03_02',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'يُدْرِيكَ',
  },
  {
    id: '80_03_03',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'لَعَلَّهُ',
  },
  {
    id: '80_03_04',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'يَزَّكَّىٰ‎﴿٣﴾',
  },
  {
    id: '80_04_01',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'أَوْ',
  },
  {
    id: '80_04_02',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'يَذَّكَّرُ',
  },
  {
    id: '80_04_03',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'فَتَنْفَعَهُ',
  },
  {
    id: '80_04_04',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'الذِّكْرَىٰ‎﴿٤﴾',
  },
  {
    id: '80_05_01',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'أَمَّا',
  },
  {
    id: '80_05_02',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'مَنِ',
  },
  {
    id: '80_05_03',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'اِسْتَغْنَىٰ‎﴿٥﴾',
  },
  {
    id: '80_06_01',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَنْتَ',
  },
  {
    id: '80_06_02',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'لَهُ',
  },
  {
    id: '80_06_03',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'تَصَدَّىٰ‎﴿٦﴾',
  },
  {
    id: '80_07_01',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '80_07_02',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'عَلَيْكَ',
  },
  {
    id: '80_07_03',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'أَلَّا',
  },
  {
    id: '80_07_04',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'يَزَّكَّىٰ‎﴿٧﴾',
  },
  {
    id: '80_08_01',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَمَّا',
  },
  {
    id: '80_08_02',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'مَنْ',
  },
  {
    id: '80_08_03',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'جَاءَكَ',
  },
  {
    id: '80_08_04',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'يَسْعَىٰ‎﴿٨﴾',
  },
  {
    id: '80_09_01',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'وَهُوَ',
  },
  {
    id: '80_09_02',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'يَخْشَىٰ‎﴿٩﴾',
  },
  {
    id: '80_10_01',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَنْتَ',
  },
  {
    id: '80_10_02',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'عَنْهُ',
  },
  {
    id: '80_10_03',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'تَلَهَّىٰ‎﴿١٠﴾',
  },
  {
    id: '80_11_01',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'كَلَّا',
  },
  {
    id: '80_11_02',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّهَا',
  },
  {
    id: '80_11_03',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'تَذْكِرَةٌ‎﴿١١﴾',
  },
  {
    id: '80_12_01',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'فَمَنْ',
  },
  {
    id: '80_12_02',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'شَاءَ',
  },
  {
    id: '80_12_03',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'ذَكَرَهُ‎﴿١٢﴾',
  },
  {
    id: '80_13_01',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'فِي',
  },
  {
    id: '80_13_02',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'صُحُفٍ',
  },
  {
    id: '80_13_03',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'مُكَرَّمَةٍ‎﴿١٣﴾',
  },
  {
    id: '80_14_01',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'مَرْفُوعَةٍ',
  },
  {
    id: '80_14_02',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'مُطَهَّرَةٍ‎﴿١٤﴾',
  },
  {
    id: '80_15_01',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'بِأَيْدِي',
  },
  {
    id: '80_15_02',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'سَفَرَةٍ‎﴿١٥﴾',
  },
  {
    id: '80_16_01',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'كِرَامٍ',
  },
  {
    id: '80_16_02',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'بَرَرَةٍ‎﴿١٦﴾',
  },
  {
    id: '80_17_01',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'قُتِلَ',
  },
  {
    id: '80_17_02',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'الْإِنْسَانُ',
  },
  {
    id: '80_17_03',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '80_17_04',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'أَكْفَرَهُ‎﴿١٧﴾',
  },
  {
    id: '80_18_01',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْ',
  },
  {
    id: '80_18_02',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'أَيِّ',
  },
  {
    id: '80_18_03',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'شَيْءٍ',
  },
  {
    id: '80_18_04',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'خَلَقَهُ‎﴿١٨﴾',
  },
  {
    id: '80_19_01',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْ',
  },
  {
    id: '80_19_02',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'نُطْفَةٍ',
  },
  {
    id: '80_19_03',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'خَلَقَهُ',
  },
  {
    id: '80_19_04',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'فَقَدَّرَهُ‎﴿١٩﴾',
  },
  {
    id: '80_20_01',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '80_20_02',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّبِيلَ',
  },
  {
    id: '80_20_03',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'يَسَّرَهُ‎﴿٢٠﴾',
  },
  {
    id: '80_21_01',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '80_21_02',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'أَمَاتَهُ',
  },
  {
    id: '80_21_03',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَقْبَرَهُ‎﴿٢١﴾',
  },
  {
    id: '80_22_01',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '80_22_02',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذَا',
  },
  {
    id: '80_22_03',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'شَاءَ',
  },
  {
    id: '80_22_04',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْشَرَهُ‎﴿٢٢﴾',
  },
  {
    id: '80_23_01',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'كَلَّا',
  },
  {
    id: '80_23_02',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'لَمَّا',
  },
  {
    id: '80_23_03',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'يَقْضِ',
  },
  {
    id: '80_23_04',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '80_23_05',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'أَمَرَهُ‎﴿٢٣﴾',
  },
  {
    id: '80_24_01',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'فَلْيَنْظُرِ',
  },
  {
    id: '80_24_02',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'الْإِنْسَانُ',
  },
  {
    id: '80_24_03',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَىٰ',
  },
  {
    id: '80_24_04',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'طَعَامِهِ‎﴿٢٤﴾',
  },
  {
    id: '80_25_01',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنَّا',
  },
  {
    id: '80_25_02',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'صَبَبْنَا',
  },
  {
    id: '80_25_03',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمَاءَ',
  },
  {
    id: '80_25_04',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'صَبًّا‎﴿٢٥﴾',
  },
  {
    id: '80_26_01',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'ثُمَّ',
  },
  {
    id: '80_26_02',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'شَقَقْنَا',
  },
  {
    id: '80_26_03',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'الْأَرْضَ',
  },
  {
    id: '80_26_04',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'شَقًّا‎﴿٢٦﴾',
  },
  {
    id: '80_27_01',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَنْبَتْنَا',
  },
  {
    id: '80_27_02',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'فِيهَا',
  },
  {
    id: '80_27_03',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'حَبًّا‎﴿٢٧﴾',
  },
  {
    id: '80_28_01',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'وَعِنَبًا',
  },
  {
    id: '80_28_02',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'وَقَضْبًا‎﴿٢٨﴾',
  },
  {
    id: '80_29_01',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'وَزَيْتُونًا',
  },
  {
    id: '80_29_02',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'وَنَخْلًا‎﴿٢٩﴾',
  },
  {
    id: '80_30_01',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'وَحَدَائِقَ',
  },
  {
    id: '80_30_02',
    verseNumber: 30,
    startTime: 0,
    endTime: 1,
    ayah: 'غُلْبًا‎﴿٣٠﴾',
  },
  {
    id: '80_31_01',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'وَفَاكِهَةً',
  },
  {
    id: '80_31_02',
    verseNumber: 31,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَبًّا‎﴿٣١﴾',
  },
  {
    id: '80_32_01',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'مَتَاعًا',
  },
  {
    id: '80_32_02',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'لَكُمْ',
  },
  {
    id: '80_32_03',
    verseNumber: 32,
    startTime: 0,
    endTime: 1,
    ayah: 'وَلِأَنْعَامِكُمْ‎﴿٣٢﴾',
  },
  {
    id: '80_33_01',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'فَإِذَا',
  },
  {
    id: '80_33_02',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'جَاءَتِ',
  },
  {
    id: '80_33_03',
    verseNumber: 33,
    startTime: 0,
    endTime: 1,
    ayah: 'الصَّاخَّةُ‎﴿٣٣﴾',
  },
  {
    id: '80_34_01',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَ',
  },
  {
    id: '80_34_02',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'يَفِرُّ',
  },
  {
    id: '80_34_03',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمَرْءُ',
  },
  {
    id: '80_34_04',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْ',
  },
  {
    id: '80_34_05',
    verseNumber: 34,
    startTime: 0,
    endTime: 1,
    ayah: 'أَخِيهِ‎﴿٣٤﴾',
  },
  {
    id: '80_35_01',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأُمِّهِ',
  },
  {
    id: '80_35_02',
    verseNumber: 35,
    startTime: 0,
    endTime: 1,
    ayah: 'وَأَبِيهِ‎﴿٣٥﴾',
  },
  {
    id: '80_36_01',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'وَصَاحِبَتِهِ',
  },
  {
    id: '80_36_02',
    verseNumber: 36,
    startTime: 0,
    endTime: 1,
    ayah: 'وَبَنِيهِ‎﴿٣٦﴾',
  },
  {
    id: '80_37_01',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'لِكُلِّ',
  },
  {
    id: '80_37_02',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'امْرِئٍ',
  },
  {
    id: '80_37_03',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْهُمْ',
  },
  {
    id: '80_37_04',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَئِذٍ',
  },
  {
    id: '80_37_05',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'شَأْنٌ',
  },
  {
    id: '80_37_06',
    verseNumber: 37,
    startTime: 0,
    endTime: 1,
    ayah: 'يُغْنِيهِ‎﴿٣٧﴾',
  },
  {
    id: '80_38_01',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'وُجُوهٌ',
  },
  {
    id: '80_38_02',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَئِذٍ',
  },
  {
    id: '80_38_03',
    verseNumber: 38,
    startTime: 0,
    endTime: 1,
    ayah: 'مُسْفِرَةٌ‎﴿٣٨﴾',
  },
  {
    id: '80_39_01',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'ضَاحِكَةٌ',
  },
  {
    id: '80_39_02',
    verseNumber: 39,
    startTime: 0,
    endTime: 1,
    ayah: 'مُسْتَبْشِرَةٌ‎﴿٣٩﴾',
  },
  {
    id: '80_40_01',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'وَوُجُوهٌ',
  },
  {
    id: '80_40_02',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'يَوْمَئِذٍ',
  },
  {
    id: '80_40_03',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'عَلَيْهَا',
  },
  {
    id: '80_40_04',
    verseNumber: 40,
    startTime: 0,
    endTime: 1,
    ayah: 'غَبَرَةٌ‎﴿٤٠﴾',
  },
  {
    id: '80_41_01',
    verseNumber: 41,
    startTime: 0,
    endTime: 1,
    ayah: 'تَرْهَقُهَا',
  },
  {
    id: '80_41_02',
    verseNumber: 41,
    startTime: 0,
    endTime: 1,
    ayah: 'قَتَرَةٌ‎﴿٤١﴾',
  },
  {
    id: '80_42_01',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'أُولَٰئِكَ',
  },
  {
    id: '80_42_02',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'هُمُ',
  },
  {
    id: '80_42_03',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكَفَرَةُ',
  },
  {
    id: '80_42_04',
    verseNumber: 42,
    startTime: 0,
    endTime: 1,
    ayah: 'الْفَجَرَةُ‎﴿٤٢﴾',
  },
];

export default surah80;
