const surah81 = [
  {
    id: '81_01_01',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذَا',
  },
  {
    id: '81_01_02',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'الشَّمْسُ',
  },
  {
    id: '81_01_03',
    verseNumber: 1,
    startTime: 0,
    endTime: 1,
    ayah: 'كُوِّرَتْ‎﴿١﴾',
  },
  {
    id: '81_02_01',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_02_02',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'النُّجُومُ',
  },
  {
    id: '81_02_03',
    verseNumber: 2,
    startTime: 0,
    endTime: 1,
    ayah: 'انْكَدَرَتْ‎﴿٢﴾',
  },
  {
    id: '81_03_01',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_03_02',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجِبَالُ',
  },
  {
    id: '81_03_03',
    verseNumber: 3,
    startTime: 0,
    endTime: 1,
    ayah: 'سُيِّرَتْ‎﴿٣﴾',
  },
  {
    id: '81_04_01',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_04_02',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'الْعِشَارُ',
  },
  {
    id: '81_04_03',
    verseNumber: 4,
    startTime: 0,
    endTime: 1,
    ayah: 'عُطِّلَتْ‎﴿٤﴾',
  },
  {
    id: '81_05_01',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_05_02',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'الْوُحُوشُ',
  },
  {
    id: '81_05_03',
    verseNumber: 5,
    startTime: 0,
    endTime: 1,
    ayah: 'حُشِرَتْ‎﴿٥﴾',
  },
  {
    id: '81_06_01',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_06_02',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'الْبِحَارُ',
  },
  {
    id: '81_06_03',
    verseNumber: 6,
    startTime: 0,
    endTime: 1,
    ayah: 'سُجِّرَتْ‎﴿٦﴾',
  },
  {
    id: '81_07_01',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_07_02',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'النُّفُوسُ',
  },
  {
    id: '81_07_03',
    verseNumber: 7,
    startTime: 0,
    endTime: 1,
    ayah: 'زُوِّجَتْ‎﴿٧﴾',
  },
  {
    id: '81_08_01',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_08_02',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمَوْءُودَةُ',
  },
  {
    id: '81_08_03',
    verseNumber: 8,
    startTime: 0,
    endTime: 1,
    ayah: 'سُئِلَتْ‎﴿٨﴾',
  },
  {
    id: '81_09_01',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'بِأَيِّ',
  },
  {
    id: '81_09_02',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'ذَنْبٍ',
  },
  {
    id: '81_09_03',
    verseNumber: 9,
    startTime: 0,
    endTime: 1,
    ayah: 'قُتِلَتْ‎﴿٩﴾',
  },
  {
    id: '81_10_01',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_10_02',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'الصُّحُفُ',
  },
  {
    id: '81_10_03',
    verseNumber: 10,
    startTime: 0,
    endTime: 1,
    ayah: 'نُشِرَتْ‎﴿١٠﴾',
  },
  {
    id: '81_11_01',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_11_02',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'السَّمَاءُ',
  },
  {
    id: '81_11_03',
    verseNumber: 11,
    startTime: 0,
    endTime: 1,
    ayah: 'كُشِطَتْ‎﴿١١﴾',
  },
  {
    id: '81_12_01',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_12_02',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجَحِيمُ',
  },
  {
    id: '81_12_03',
    verseNumber: 12,
    startTime: 0,
    endTime: 1,
    ayah: 'سُعِّرَتْ‎﴿١٢﴾',
  },
  {
    id: '81_13_01',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'وَإِذَا',
  },
  {
    id: '81_13_02',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجَنَّةُ',
  },
  {
    id: '81_13_03',
    verseNumber: 13,
    startTime: 0,
    endTime: 1,
    ayah: 'أُزْلِفَتْ‎﴿١٣﴾',
  },
  {
    id: '81_14_01',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'عَلِمَتْ',
  },
  {
    id: '81_14_02',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'نَفْسٌ',
  },
  {
    id: '81_14_03',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'مَا',
  },
  {
    id: '81_14_04',
    verseNumber: 14,
    startTime: 0,
    endTime: 1,
    ayah: 'أَحْضَرَتْ‎﴿١٤﴾',
  },
  {
    id: '81_15_01',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'فَلَا',
  },
  {
    id: '81_15_02',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'أُقْسِمُ',
  },
  {
    id: '81_15_03',
    verseNumber: 15,
    startTime: 0,
    endTime: 1,
    ayah: 'بِالْخُنَّسِ‎﴿١٥﴾',
  },
  {
    id: '81_16_01',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'الْجَوَارِ',
  },
  {
    id: '81_16_02',
    verseNumber: 16,
    startTime: 0,
    endTime: 1,
    ayah: 'الْكُنَّسِ‎﴿١٦﴾',
  },
  {
    id: '81_17_01',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'وَاللَّيْلِ',
  },
  {
    id: '81_17_02',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذَا',
  },
  {
    id: '81_17_03',
    verseNumber: 17,
    startTime: 0,
    endTime: 1,
    ayah: 'عَسْعَسَ‎﴿١٧﴾',
  },
  {
    id: '81_18_01',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'وَالصُّبْحِ',
  },
  {
    id: '81_18_02',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'إِذَا',
  },
  {
    id: '81_18_03',
    verseNumber: 18,
    startTime: 0,
    endTime: 1,
    ayah: 'تَنَفَّسَ‎﴿١٨﴾',
  },
  {
    id: '81_19_01',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنَّهُ',
  },
  {
    id: '81_19_02',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'لَقَوْلُ',
  },
  {
    id: '81_19_03',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'رَسُولٍ',
  },
  {
    id: '81_19_04',
    verseNumber: 19,
    startTime: 0,
    endTime: 1,
    ayah: 'كَرِيمٍ‎﴿١٩﴾',
  },
  {
    id: '81_20_01',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'ذِي',
  },
  {
    id: '81_20_02',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'قُوَّةٍ',
  },
  {
    id: '81_20_03',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'عِنْدَ',
  },
  {
    id: '81_20_04',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'ذِي',
  },
  {
    id: '81_20_05',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'الْعَرْشِ',
  },
  {
    id: '81_20_06',
    verseNumber: 20,
    startTime: 0,
    endTime: 1,
    ayah: 'مَكِينٍ‎﴿٢٠﴾',
  },
  {
    id: '81_21_01',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'مُطَاعٍ',
  },
  {
    id: '81_21_02',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'ثَمَّ',
  },
  {
    id: '81_21_03',
    verseNumber: 21,
    startTime: 0,
    endTime: 1,
    ayah: 'أَمِينٍ‎﴿٢١﴾',
  },
  {
    id: '81_22_01',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '81_22_02',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'صَاحِبُكُمْ',
  },
  {
    id: '81_22_03',
    verseNumber: 22,
    startTime: 0,
    endTime: 1,
    ayah: 'بِمَجْنُونٍ‎﴿٢٢﴾',
  },
  {
    id: '81_23_01',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'وَلَقَدْ',
  },
  {
    id: '81_23_02',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'رَءَاهُ',
  },
  {
    id: '81_23_03',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'بِالْأُفُقِ',
  },
  {
    id: '81_23_04',
    verseNumber: 23,
    startTime: 0,
    endTime: 1,
    ayah: 'الْمُبِينِ‎﴿٢٣﴾',
  },
  {
    id: '81_24_01',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '81_24_02',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'هُوَ',
  },
  {
    id: '81_24_03',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'عَلَى',
  },
  {
    id: '81_24_04',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'الْغَيْبِ',
  },
  {
    id: '81_24_05',
    verseNumber: 24,
    startTime: 0,
    endTime: 1,
    ayah: 'بِضَنِينٍ‎﴿٢٤﴾',
  },
  {
    id: '81_25_01',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '81_25_02',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'هُوَ',
  },
  {
    id: '81_25_03',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'بِقَوْلِ',
  },
  {
    id: '81_25_04',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'شَيْطَانٍ',
  },
  {
    id: '81_25_05',
    verseNumber: 25,
    startTime: 0,
    endTime: 1,
    ayah: 'رَجِيمٍ‎﴿٢٥﴾',
  },
  {
    id: '81_26_01',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'فَأَيْنَ',
  },
  {
    id: '81_26_02',
    verseNumber: 26,
    startTime: 0,
    endTime: 1,
    ayah: 'تَذْهَبُونَ‎﴿٢٦﴾',
  },
  {
    id: '81_27_01',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'إِنْ',
  },
  {
    id: '81_27_02',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'هُوَ',
  },
  {
    id: '81_27_03',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَّا',
  },
  {
    id: '81_27_04',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'ذِكْرٌ',
  },
  {
    id: '81_27_05',
    verseNumber: 27,
    startTime: 0,
    endTime: 1,
    ayah: 'لِلْعَالَمِينَ‎﴿٢٧﴾',
  },
  {
    id: '81_28_01',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'لِمَنْ',
  },
  {
    id: '81_28_02',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'شَاءَ',
  },
  {
    id: '81_28_03',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'مِنْكُمْ',
  },
  {
    id: '81_28_04',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْ',
  },
  {
    id: '81_28_05',
    verseNumber: 28,
    startTime: 0,
    endTime: 1,
    ayah: 'يَسْتَقِيمَ‎﴿٢٨﴾',
  },
  {
    id: '81_29_01',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'وَمَا',
  },
  {
    id: '81_29_02',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'تَشَاءُونَ',
  },
  {
    id: '81_29_03',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'إِلَّا',
  },
  {
    id: '81_29_04',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'أَنْ',
  },
  {
    id: '81_29_05',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'يَشَاءَ',
  },
  {
    id: '81_29_06',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'اللَّهُ',
  },
  {
    id: '81_29_07',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'رَبُّ',
  },
  {
    id: '81_29_08',
    verseNumber: 29,
    startTime: 0,
    endTime: 1,
    ayah: 'الْعَالَمِينَ‎﴿٢٩﴾',
  },
];

export default surah81;
